name: ci

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@main
        with:
          deno-version: "1.41.2"
      - name: Run fmt
        run: |
          deno fmt --check
      - name: Run lint
        run: |
          deno lint
      - name: Run diff README
        shell: bash
        run: |
          diff README.md <(deno run --allow-run --allow-read=examples scripts/readme.ts)
      - name: Run tests
        run: |
          deno test -A --coverage=coverage
      - name: Create coverage report
        run: |
          deno coverage ./coverage --lcov > coverage.lcov
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.lcov
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
